# Template should be populated using populate_config_template.py

apiVersion: v1
kind: Service
metadata:
  name: %(environment)s-%(owner)s-lb-blorg-fe
  labels:
    app: blorg
    owner: %(owner)s
    environment: %(environment)s
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: blorg
    owner: %(owner)s
    environment: %(environment)s
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: %(environment)s-%(owner)s-blorg-fe
spec:
  selector:
    matchLabels:
      app: blorg
      owner: %(owner)s
      environment: %(environment)s
      tier: frontend
  template:
    metadata:
      name: %(environment)s-%(owner)s-blorg-fe
      labels:
        app: blorg
        owner: %(owner)s
        environment: %(environment)s
        tier: frontend
    spec:
      containers:
      - name: frontend
        imagePullPolicy: Always
        image: %(imgname)s
        command: [
          "./server",
          "--backendAddr", "%(backend_addr)s"
        ]
        ports:
        - containerPort: 8081
